name: unified_distributor
description: A powerful and efficient tool for packaging and publishing your applications with ease.
version: 0.2.2
publish_to: none
homepage: https://fastforge.dev
repository: https://github.com/fastforgedev/fastforge/tree/main/packages/unified_distributor
issue_tracker: https://github.com/fastforgedev/fastforge/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.2.0
  charset: ^2.0.1
  dio: ^5.3.4
  flutter_app_builder: ^0.6.0
  flutter_app_packager:
    path: ../flutter_app_packager
  flutter_app_publisher: ^0.6.2
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.1.0
  shell_executor: ^0.3.0
  shell_uikit: ^0.3.0
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
  mostly_reasonable_lints: ^0.1.2
  test: ^1.23.1
